# Versão da sintaxe do docker-compose
version: '3.8'

# Definição dos serviços (contêineres) que farão parte do nosso ambiente
services:
  # O nome do nosso serviço de banco de dados. Pode ser qualquer nome.
  postgres-db:
    # A imagem oficial do PostgreSQL que será baixada do Docker Hub.
    # '16' refere-se à versão principal. Você pode usar '15', '14', etc.
    image: postgres:16
    
    # Nome do contêiner para fácil identificação
    container_name: trabalho_bd
    
    # Reinicia o contêiner automaticamente se ele parar por algum motivo
    restart: always
    
    # Variáveis de ambiente para configurar o PostgreSQL na primeira inicialização
    environment:
      POSTGRES_USER: user       # Defina aqui o seu usuário
      POSTGRES_PASSWORD: senha   # Defina aqui a sua senha
      POSTGRES_DB: meubanco         # Defina aqui o nome do banco de dados a ser criado
      
    # Mapeamento de portas. Conecta a porta 5432 do seu computador (host)
    # à porta 5432 do contêiner (onde o Postgres está rodando).
    ports:
      - "5432:5432"
      
    # Volumes para persistir os dados. ESSENCIAL para não perder seu trabalho!
    # Isso cria uma pasta 'db_data' no seu computador e a sincroniza com a pasta
    # onde o PostgreSQL guarda os dados dentro do contêiner.
    volumes:
      - ./db_data:/var/lib/postgresql/data