import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Main from "./components/Main";
import LocalizationDateProvider from "./localizationDateProvider";

export const metadata: Metadata = {
  title: "Sistema Médico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <LocalizationDateProvider>
          <Header />
          <Main>{children}</Main>
        </LocalizationDateProvider>
      </body>
    </html>
  );
}
