import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Main from "./components/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Header />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
